// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBoTo.Data;

#nullable disable

namespace WebBoTo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260324173922_AddTinTucVaDanhGia")]
    partial class AddTinTucVaDanhGia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBoTo.Models.ChiTietDatBan", b =>
                {
                    b.Property<int>("Id_CTDB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_CTDB"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Id_DatBan")
                        .HasColumnType("int");

                    b.Property<int>("Id_MonAn")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id_CTDB");

                    b.ToTable("ChiTietDatBan");
                });

            modelBuilder.Entity("WebBoTo.Models.DanhGia", b =>
                {
                    b.Property<int>("Id_DanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DanhGia"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_TK")
                        .HasColumnType("int");

                    b.Property<bool>("IsNoiBat")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoSao")
                        .HasColumnType("int");

                    b.HasKey("Id_DanhGia");

                    b.HasIndex("Id_TK");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebBoTo.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id_DM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_DanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DM"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_DM");

                    b.ToTable("DanhMuc");

                    b.HasData(
                        new
                        {
                            Id_DM = 1,
                            TenDanhMuc = "Luộc"
                        },
                        new
                        {
                            Id_DM = 2,
                            TenDanhMuc = "Hấp"
                        },
                        new
                        {
                            Id_DM = 3,
                            TenDanhMuc = "Nướng"
                        },
                        new
                        {
                            Id_DM = 4,
                            TenDanhMuc = "Nhúng"
                        },
                        new
                        {
                            Id_DM = 5,
                            TenDanhMuc = "Lẩu"
                        },
                        new
                        {
                            Id_DM = 6,
                            TenDanhMuc = "Cháo"
                        },
                        new
                        {
                            Id_DM = 7,
                            TenDanhMuc = "Gà"
                        },
                        new
                        {
                            Id_DM = 8,
                            TenDanhMuc = "Tôm"
                        },
                        new
                        {
                            Id_DM = 9,
                            TenDanhMuc = "Mực"
                        },
                        new
                        {
                            Id_DM = 10,
                            TenDanhMuc = "Chiên"
                        },
                        new
                        {
                            Id_DM = 11,
                            TenDanhMuc = "Xào"
                        },
                        new
                        {
                            Id_DM = 12,
                            TenDanhMuc = "Nước Ngọt"
                        },
                        new
                        {
                            Id_DM = 13,
                            TenDanhMuc = "Bia - Rượu"
                        },
                        new
                        {
                            Id_DM = 14,
                            TenDanhMuc = "Tráng miệng"
                        });
                });

            modelBuilder.Entity("WebBoTo.Models.DatBan", b =>
                {
                    b.Property<int>("Id_DatBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_DatBan"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("GioDat")
                        .HasColumnType("time");

                    b.Property<int?>("Id_NhanVienDuyet")
                        .HasColumnType("int");

                    b.Property<int>("Id_TK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongNguoi")
                        .HasColumnType("int");

                    b.Property<string>("TenNhanVienDuyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TienCoc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id_DatBan");

                    b.ToTable("DatBan");
                });

            modelBuilder.Entity("WebBoTo.Models.HinhAnhDanhGia", b =>
                {
                    b.Property<int>("Id_HinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_HinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_DanhGia")
                        .HasColumnType("int");

                    b.HasKey("Id_HinhAnh");

                    b.HasIndex("Id_DanhGia");

                    b.ToTable("HinhAnhDanhGia");
                });

            modelBuilder.Entity("WebBoTo.Models.MenuTiec", b =>
                {
                    b.Property<int>("Id_MenuTiec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MenuTiec"));

                    b.Property<string>("DanhSachMonAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_MenuTiec");

                    b.ToTable("MenuTiec");
                });

            modelBuilder.Entity("WebBoTo.Models.MonAn", b =>
                {
                    b.Property<int>("Id_MonAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_MonAn"));

                    b.Property<int>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDacTrung")
                        .HasColumnType("bit");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_MonAn");

                    b.HasIndex("DanhMucId");

                    b.ToTable("MonAn");
                });

            modelBuilder.Entity("WebBoTo.Models.TaiKhoan", b =>
                {
                    b.Property<int>("Id_TK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_TK"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_TK");

                    b.ToTable("TaiKhoan");

                    b.HasData(
                        new
                        {
                            Id_TK = 1,
                            Email = "admin@webboto.vn",
                            HoTen = "Admin",
                            MatKhau = "Admin@123",
                            SoDienThoai = "0123456789",
                            TrangThai = true,
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("WebBoTo.Models.ThongBao", b =>
                {
                    b.Property<int>("Id_ThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_ThongBao"));

                    b.Property<int>("Id_TK")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_ThongBao");

                    b.HasIndex("Id_TK");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("WebBoTo.Models.DanhGia", b =>
                {
                    b.HasOne("WebBoTo.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("Id_TK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebBoTo.Models.HinhAnhDanhGia", b =>
                {
                    b.HasOne("WebBoTo.Models.DanhGia", "DanhGia")
                        .WithMany("HinhAnhDanhGias")
                        .HasForeignKey("Id_DanhGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("WebBoTo.Models.MonAn", b =>
                {
                    b.HasOne("WebBoTo.Models.DanhMuc", "DanhMuc")
                        .WithMany("MonAns")
                        .HasForeignKey("DanhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("WebBoTo.Models.ThongBao", b =>
                {
                    b.HasOne("WebBoTo.Models.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("Id_TK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("WebBoTo.Models.DanhGia", b =>
                {
                    b.Navigation("HinhAnhDanhGias");
                });

            modelBuilder.Entity("WebBoTo.Models.DanhMuc", b =>
                {
                    b.Navigation("MonAns");
                });
#pragma warning restore 612, 618
        }
    }
}
